apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "my-quarkus-app51"
  annotations:
    argocd/app-name: my-quarkus-app51-dev
    backstage.io/kubernetes-id: my-quarkus-app51
    backstage.io/kubernetes-namespace: my-quarkus-app51-dev
    janus-idp.io/tekton-enabled : 'false'
    teamcity/project-id: TEAMCITY_NAME
    github.com/project-slug: janus-idp-demo/backstage-sample-quarkus-app51
    backstage.io/techdocs-ref: dir:.
  tags:
    - java
    - quarkus
  links:
    - url: https://devspaces.apps.cluster-fjxjm.fjxjm.sandbox1445.opentlc.com/#https://github.com/janus-idp-demo/backstage-sample-quarkus-app51?che-editor=che-incubator/che-code/insiders&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: https://devspaces.apps.cluster-fjxjm.fjxjm.sandbox1445.opentlc.com/#https://github.com/janus-idp-demo/backstage-sample-quarkus-app51?che-editor=che-incubator/che-idea/latest&devfilePath=.devfile-intellij.yaml
      title: OpenShift Dev Spaces (JetBrains IntelliJ)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/jayfray12"
  providesApis:
    - "my-quarkus-app51"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "my-quarkus-app51"
spec:
  type: openapi
  lifecycle: production
  owner: "user:default/jayfray12"
  definition:
    $text: ./openapi.yaml
